::__tagarray <-  [
    "popext_forceromevision"
    "popext_addcond|32|10"
    "popext_addcond|87|99999999"
    "popext_addcond|71|99999999"
    "popext_usehumanmodel"
    "popext_alwaysglow"
    "popext_usebestweapon"
    "popext_giveweapon|tf_weapon_shotgun_pyro|425"
    "popext_giveweapon|tf_weapon_revolver|425"
    "popext_giveweapon|tf_weapon_drg_pomson|588"
    "popext_homingprojectile|0.5|0.5"
    "popext_improvedairblast"
    "popext_usehumananims"
    "popext_spell|11|5|2"
    "popext_ringoffire|20|2"
    "popext_weaponswitch|2"
    "popext_fireweapon|2048"
    "popext_meleeai"
    "popext_dispenseroverride|2"
    "popext_weaponresist|298|20"
    "popext_rocketcustomtrail|eyeboss_projectile"
    "popext_reprogrammed"
    "popext_setskin|0"
    "popext_mobber"
    "popext_halloweenboss|headless_hatman|5000|223 285 -517|99999|3"
    "popext_halloweenboss|eyeball_boss|3000|752 4529 389|60"
    "popext_usecustommodel|models/empty.mdl"
    "popext_usecustommodel|models/empty.mdl"
    "popext_usecustommodel|models/bots/spy/bot_spy.mdl"
    "popext_teleportnearvictim"
    "popext_usecustommodel|models/bots/engineer/bot_engineer.mdl"
    "popext_spawnhere|4192.6 2577.0 -21.0|1.5" // infront of red spawn
    "popext_spawnhere|4918.6 2573.5 -21.0|1.5" // infront of red spawn
]